package appbibliotecanuevo.Vistas;


import appbibliotecanuevo.AccesoDatos.EjemplarData;
import appbibliotecanuevo.AccesoDatos.LectorData;
import appbibliotecanuevo.AccesoDatos.PrestamoData;
import appbibliotecanuevo.entidades.Ejemplar;
import appbibliotecanuevo.entidades.EstadoEjemplar;
import appbibliotecanuevo.entidades.Lector;
import appbibliotecanuevo.entidades.Prestamo;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class GenerarPrestamo1 extends javax.swing.JPanel {

    Prestamo prestamo;
PrestamoData presData=new PrestamoData();

    public GenerarPrestamo1() {
        initComponents();
      
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtidPrestamo = new javax.swing.JTextField();
        jTxtidLector = new javax.swing.JTextField();
        jTxtidEjemplar = new javax.swing.JTextField();
        jTxtFechaPrestamo = new javax.swing.JTextField();
        jTxtFechaDevolucion = new javax.swing.JTextField();
        jBbUSCAR = new javax.swing.JButton();
        jBnuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBELIMINAR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTxtBusquedaporId = new javax.swing.JTextField();
        jTxtESTADO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("GENERAR PRESTAMOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ID PRESTAMO:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ID LECTOR:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ID EJEMPLAR:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("FECHA PRESTAMO:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("FECHA DEVOLUCION:");

        jTxtidEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtidEjemplarActionPerformed(evt);
            }
        });

        jBbUSCAR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBbUSCAR.setText("BUSCAR");
        jBbUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbUSCARActionPerformed(evt);
            }
        });

        jBnuevo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBnuevo.setText("NUEVO");
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });

        jBGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBGuardar.setText("GUARDAR");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBELIMINAR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBELIMINAR.setText("ELIMINAR");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("BUSQUEDA POR ID:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ESTADO:");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtidEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBnuevo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtFechaPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtESTADO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(232, 232, 232)
                                .addComponent(jTxtidLector, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(203, 203, 203)
                                .addComponent(jTxtidPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jBbUSCAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtBusquedaporId, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBGuardar)
                .addGap(69, 69, 69)
                .addComponent(jBELIMINAR)
                .addGap(145, 145, 145))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtBusquedaporId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbUSCAR))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtidPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtidLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtidEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTxtESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBELIMINAR)
                    .addComponent(jBGuardar)
                    .addComponent(jBnuevo))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtidEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtidEjemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtidEjemplarActionPerformed
//jTxtFechaDevolucion;
//    private javax.swing.JTextField jTxtFechaPrestamo;
//    private javax.swing.JTextField jTxtidEjemplar;
//    private javax.swing.JTextField jTxtidLector;
//    private javax.swing.JTextField jTxtidPrestamo;
    // End of variables declaration                   
    private void jBbUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbUSCARActionPerformed
        // TODO add your handling code here:                                   
        try {
            Integer id = Integer.parseInt(jTxtBusquedaporId.getText());
            prestamo = presData.obtenerPresPorLector(id);
            if (prestamo != null) {
                String idPrestamo = String.valueOf(prestamo.getIdPrestamo());
                jTxtidPrestamo.setText(idPrestamo);
                String codigo = String.valueOf(prestamo.getIdEjemplar());
                jTxtidEjemplar.setText(codigo);
                String nroSocio = String.valueOf(prestamo.getIdLector());
               jTxtidLector.setText(nroSocio);
               String fecha = prestamo.getFechaPrestamo();
                //SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
                jTxtFechaPrestamo.setText(fecha);
                String fecha2 = prestamo.getFechaDevolucion();
                //SimpleDateFormat formatoFecha2 = new SimpleDateFormat("dd/MM/yyyy");
                jTxtFechaDevolucion.setText(fecha2);
                String estado = String.valueOf(prestamo.getEstado());
                jTxtESTADO.setText(estado);
            } else {
                // JOptionPane.showMessageDialog(this,"No existe un prestamp con el ID proporcionado" );
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ingrese un numero valido " + e.getMessage());
        }
    
    }//GEN-LAST:event_jBbUSCARActionPerformed


    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        
        
        
        try {
            
        String idText = jTxtidPrestamo.getText();
        String codigoText = jTxtidEjemplar.getText();
        String nroSocioText = jTxtidLector.getText();
        String fechaIniText = jTxtFechaPrestamo.getText();
        String fechaFinText = jTxtFechaDevolucion.getText();
        String estadoText = jTxtESTADO.getText();

        if (idText.isEmpty() || codigoText.isEmpty() || nroSocioText.isEmpty() || fechaIniText.isEmpty() || fechaFinText.isEmpty() || estadoText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacíos.");
            return;
        }

        Integer idPrestamo = Integer.parseInt(idText);
        Integer codigo = Integer.parseInt(codigoText);
        Integer nroSocio = Integer.parseInt(nroSocioText);
        EstadoEjemplar estado= EstadoEjemplar.valueOf(estadoText);

        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy/MM/DD");
        java.util.Date fechaInicioPrestamo = formatoFecha.parse(fechaIniText);
        java.util.Date fechaFinPrestamo = formatoFecha.parse(fechaFinText);

        // Convierte las fechas de java.util.Date a java.sql.Date
        java.sql.Date sqlFechaInicioPrestamo = new java.sql.Date(fechaInicioPrestamo.getTime());
        java.sql.Date sqlFechaFinPrestamo = new java.sql.Date(fechaFinPrestamo.getTime());

        
        //Boolean estado = Boolean.parseBoolean(estadoText);
        Integer idE=Integer.parseInt(codigoText);
        EjemplarData ejeData = new EjemplarData();
        Ejemplar ejemplar = new Ejemplar();
        
        ejemplar=ejeData.buscarEjemplar(idE);
        
         Integer idL=Integer.parseInt(nroSocioText);
        LectorData lecData = new LectorData();
        Lector lector = new Lector();
        lector=lecData.buscarLector(idL);
        
        if (sqlFechaInicioPrestamo.after(sqlFechaFinPrestamo)) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser posterior a la fecha de fin.");
            return;
        }
         
        // formateador de fechas
         SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
         
         //define el formato deseado
         
         String fecha1=dateFormat.format(sqlFechaInicioPrestamo);
         String fecha2=dateFormat.format(sqlFechaFinPrestamo);
        
         
                
        // Verificar si el ejemplar está prestado en las fechas seleccionadas
        if (presData.ejemplarPrestadoFechas(codigo, fecha1,  fecha2)) {
        JOptionPane.showMessageDialog(this, "El ejemplar ya está prestado en ese período de tiempo. Elija otras fechas.");
            return;
        }
        if (prestamo == null) {
            
            prestamo = new Prestamo(fecha1, fecha2, ejemplar, lector,  estado);
            presData.guardarPrestamo(prestamo);
            JOptionPane.showMessageDialog(this, "El que ID se genera de manera automatica,  el programa le asigno: " + prestamo.getIdPrestamo());
        } else {
            
            prestamo.setEjemplar(ejemplar);
            prestamo.setLector(lector);
            prestamo.setFechaPrestamo(fecha1);
            prestamo.setFechaDevolucion(fecha2);
            prestamo.setEstado(estado);
            presData.actualizarPrestamo(prestamo.getIdPrestamo(), ejemplar.getIdEjemplar(), lector.getIdLector(), fecha1, fecha2,  estado);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar o modificar el préstamo: " + e.getMessage());
    }

    
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnuevoActionPerformed

    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton jBELIMINAR;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBbUSCAR;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtBusquedaporId;
    private javax.swing.JTextField jTxtESTADO;
    private javax.swing.JTextField jTxtFechaDevolucion;
    private javax.swing.JTextField jTxtFechaPrestamo;
    private javax.swing.JTextField jTxtidEjemplar;
    private javax.swing.JTextField jTxtidLector;
    private javax.swing.JTextField jTxtidPrestamo;
    // End of variables declaration//GEN-END:variables
}